### ISSUE TITLE
Status check for 'Create a release' - Ends in Infinite loop despite the release was completed successfully

### ISSUE THREAD

**Issue by srikanthnd** [dmitryserbin/azdev-release-orchestrator#46] opened 2020-08-17 14:22 UTC
when I use this task to "Create a release" as "Release Strategy" instead of "Latest Release" or "Specific Release", it apparently gets in to the infinite loop and shows the status as not completed even though the release is completed successfully.

![image](https://user-images.githubusercontent.com/9609176/90406568-a58e1800-e0a5-11ea-9a00-1e39dbc3debc.png)

![image](https://user-images.githubusercontent.com/9609176/90406470-81cad200-e0a5-11ea-9417-2a0212bc447e.png)

![image](https://user-images.githubusercontent.com/9609176/90406615-b9397e80-e0a5-11ea-9ebb-91ce444302c0.png)

**Comment by dmitryserbin** [comment] 2020-08-17 20:33
Thanks for reporting this. The log above references a stage called "Test", but on the screenshot you show stage "Dev" instead. Could you please confirm? If you want to deploy a particular stage from the release, you need to specify the stage name in the task, otherwise it will try to release them all according to triggers in the pipeline.

Also, a full log would be helpful, if possible, his might be just a bug.

**Comment by dmitryserbin** [comment] 2020-09-17 19:16
I am going to close this, but if the issue is still actual please feel free to re-open the ticket.

**Closed by dmitryserbin** 2020-09-17 19:16 UTC
